// eslint-disable-next-line
export const LIST_ACTIONS = {
  ITEM_PREVIEW: 'ITEM_PREVIEW',
  ITEM_VIEW: 'ITEM_VIEW',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_CLEAR: 'ITEM_CLEAR',
  MINE_TRIGGER: 'MINE_TRIGGER',
  'LOGGED_IN': 'LOGGED_IN',
  'LOGIN_FAILED': 'LOGIN_FAILED'
};
