// eslint-disable-next-line
export const LIST_ACTIONS = {
  ITEM_PREVIEW: 'ITEM_PREVIEW',
  ITEM_VIEW: 'ITEM_VIEW',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_CLEAR: 'ITEM_CLEAR',
  MINE_TRIGGER: 'MINE_TRIGGER',
  CHANGE_FORM : 'CHANGE_FORM',
  SET_AUTH : 'SET_AUTH',
  SENDING_REQUEST : 'SENDING_REQUEST',
  SET_ERROR_MESSAGE : 'SET_ERROR_MESSAGE'
};
