// eslint-disable-next-line
export const LIST_ACTIONS = {
  ITEM_PREVIEW: 'ITEM_PREVIEW',
  ITEM_VIEW: 'ITEM_VIEW',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_CLEAR: 'ITEM_CLEAR',
  MINE_TRIGGER: 'MINE_TRIGGER'
};

export const USER_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGGING_IN: 'LOGGING_IN',
  LOGGED_IN: 'LOGGED_IN',
  LOGOUT: 'LOGOUT',
  LOGGING_OUT: 'LOGGING_OUT',
  LOGGED_OUT: 'LOGGED_OUT',
  SIGNUP: 'SIGNUP',
  SIGNING_UP: 'SIGNING_UP'
}

export const PROFILE_ACTIONS = {
  SET_ABOUT_ME_TEXT: 'SET_ABOUT_ME_TEXT',
  SET_SKILLS_SHARP_TEXT:'SET_SKILLS_SHARP_TEXT',
  SET_NEXT_STEPS_TEXT:'SET_NEXT_STEPS_TEXT',
  EDIT_PROFILE: 'EDIT_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_FINISHED:'UPDATE_FINISHED',
	SAVE_PROFILE_UPDATE: 'SAVE_PROFILE_UPDATE'
}
